#!/usr/bin/env python3
"""Build the full 80-lesson curriculum for Paruski."""
import json
from collections import defaultdict, Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

with open(ROOT / "content/lessons.json") as f:
    existing = json.load(f)
with open(ROOT / "content/exercises.json") as f:
    ex = json.load(f)

title_map = {l["id"]: l["title"] for l in existing}
summary_map = {l["id"]: l.get("summary","") for l in existing}

ex_by = defaultdict(int)
exam_by = defaultdict(lambda: defaultdict(int))
for e in ex:
    ex_by[e["lesson"]] += 1
    if e.get("unlock_exam"):
        exam_by[e["lesson"]][e.get("exam_kind","?")] += 1

def status(l):
    if l > 5: return "planned"
    t = ex_by.get(l, 0)
    e = sum(exam_by.get(l, {}).values())
    if t >= 300 and e >= 10: return "complete"
    if t > 0: return "partial"
    return "needs_review"

def exam_ok(l):
    if l > 5: return {"vocabulary":False,"grammar":False,"mixed":False,"full":False}
    d = dict(exam_by.get(l, {}))
    return {"vocabulary": d.get("vocabulary",0)>=5, "grammar": d.get("grammar",0)>=5,
            "mixed": d.get("mixed",0)>=5, "full": d.get("full",0)>=1}

# Full lesson data per level band
levels = []
levels.extend(["A0"] * 5)        # L1-L5
levels.extend(["A0-A1"] * 5)     # L6-L10
levels.extend(["A1"] * 18)       # L11-L28
levels.extend(["A1-A2"] * 12)    # L29-L40
levels.extend(["A2"] * 20)       # L41-L60
levels.extend(["A2-B1"] * 20)    # L61-L80

themes = [
    "Identidad","Lugar","Identidad social","Acción","Actividad",
    "Gramática verbal","Personas","Comunicación","Cantidad","Cualidad",
    "Posesión","Ausencia","Cualidad","Descripción","Ubicación",
    "Espacio","Tiempo pasado","Tiempo","Objeto","Personas",
    "Preferencia","Futuro","Futuro existencia","Cantidad","Compras",
    "Alimentación","Pertenencia","Tema","Percepción","Transacciones",
    "Ocio","Dirección","Movimiento","Contraste","Transporte",
    "Medios","Capacidad","Causalidad","Descripción","Comparación",
    "Físico","Servicios","Señalamiento","Totalidad","Salud",
    "Obligación","Genitivo I","Genitivo II","Posesivos","Personas II",
    "Ubicación II","Tiempo relativo","Procedencia","Procedencia II","Cantidad II",
    "Cantidad III","Tiempo II","Duración","Ausencia II","Personas III",
    "Aspecto","Aspecto II","Aspecto III","Aspecto IV","Aspecto V",
    "Aspecto VI","Aspecto VII","Aspecto VIII","Aspecto IX","Aspecto X",
    "Aspecto XI","Aspecto XII","Aspecto XIII","Aspecto XIV","Aspecto XV",
    "Aspecto XVI","Aspecto XVII","Aspecto XVIII","Aspecto XIX","Aspecto XX"]

obj_comm = [
    "Preguntar quién es alguien","Preguntar y responder dónde está algo",
    "Presentarse","Describir acciones cotidianas","Preguntar qué hace alguien",
    "Conjugar verbos de 2ª","Usar objeto directo animado",
    "Preguntar y decir nombres","Formar plurales","Describir cómo se hace algo",
    "Expresar posesión","Negar posesión","Describir con adjetivos",
    "Describir colores","Ubicar en prepositivo",
    "Describir posiciones","Narrar en pasado",
    "Hablar del tiempo","Usar acusativo femenino",
    "Usar acusativo animado","Expresar gustos",
    "Expresar futuro","Expresar existencia futura",
    "Preguntar la hora","Preguntar precios",
    "Pedir comida","Expresar pertenencia",
    "Expresar tema","Distinguir percepción acción/resultado",
    "Expresar pagos","Distinguir juegos e instrumentos",
    "Distinguir ubicación de dirección","Elegir идти/ходить",
    "Distinguir haber estado de haber ido","Usar ехать/ездить",
    "Expresar medio de transporte","Expresar capacidad y permiso",
    "Explicar causas","Describir con precisión",
    "Comparar","Describir físicamente",
    "Hacer pedidos","Señalar objetos",
    "Expresar totalidad","Expresar síntomas",
    "Expresar obligación","Expresar ausencia y cantidad",
    "Expresar pertenencia","Usar posesivos personales",
    "Usar acusativo animado masc.","Describir lugares con adjetivos",
    "Expresar tiempo relativo","Expresar procedencia",
    "Expresar origen concreto","Usar números 1-4",
    "Expresar genitivo plural","Decir hora precisa",
    "Expresar duraciones","Expresar ausencia temporal",
    "Formar genitivo plural animado","Comprender el aspecto verbal",
    "Usar imperfectivo","Formar perfectivo",
    "Usar perfectivo de cierre","Usar negación aspectual",
    "Usar subordinadas temporales","Expresar resultados cuantificables",
    "Expresar resultados visibles","Expresar inicio y cambio",
    "Expresar obligaciones cumplidas","Elegir aspecto correcto",
    "Prometer con futuro perfectivo","Expresar intención completiva",
    "Expresar probabilidad","Hacer peticiones corteses",
    "Expresar repetición","Usar infinitivo perfectivo con modales",
    "Usar infinitivo imperfectivo con proceso","Matizar deseo con aspecto",
    "Integrar todos los aspectos"]

obj_gram = [
    "Это + N. Кто/что это? Negación con не.",
    "Género. Он/она/оно. Adverbios de ubicación.",
    "Pronombre + profesión sin cópula. Вы cortesía.",
    "1ª conjugación (-ать/-ять). Presente.",
    "Acusativo fem. (-а→-у). Играть в + acus.",
    "2ª conjugación (-ить/-еть). Alternancias.",
    "Acusativo animado. Pronombres objeto directo.",
    "Спрашивать/отвечать/звать. Как тебя зовут.",
    "Plural regular e irregular.",
    "Adverbios de modo y grado. Predicativos impersonales.",
    "У + gen + есть. Posesión.",
    "Нет + gen. Omisión de есть.",
    "Concordancia adjetivo-sustantivo.",
    "Adjetivos de color. Concordancias especiales.",
    "Prepositivo в/на. Terminaciones -е/-и.",
    "Рядом с, около, слева от, справа от, напротив.",
    "Pasado en -л. Был/была/было/были.",
    "Días, meses, estaciones. Было impersonal.",
    "Acusativo fem. (-а→-у, -я→-ю), excepciones.",
    "Acusativo animado masc. (-а/-я). Кого?",
    "Любить (б→бл). Любить + N/inf/когда.",
    "Буду + inf. В + día.",
    "Будет/будут. У + gen + будет.",
    "Числа 1-20. Час/часа/часов. Во сколько.",
    "Сколько стоит/стоят. Стоить pasado/futuro.",
    "Есть (ем, ешь). Пить (пью, пьёшь). Comidas.",
    "Мой/твой/наш/ваш. Его/её/их. Чей?",
    "О/об + prepositivo. О ком, о чём.",
    "Слушать/слышать, смотреть/видеть, выглядеть.",
    "Платить за + acus. Frequency adverbs.",
    "Играть в/на. Играть роль.",
    "Где vs куда. Дома/домой. Здесь/сюда.",
    "Идти (irreg). Ходить. Contraste concreto/habitual.",
    "Был где vs ходил куда.",
    "Ехать (irreg). Ездить. Contraste con идти/ходить.",
    "На + transporte. На чём. Пешком.",
    "Уметь + inf. Мочь (могу). Можно/нельзя + inf.",
    "Почему, потому что, поэтому.",
    "Concordancia adj. reforzada. Adjetivos nuevos.",
    "Самый + adj. Чем + nominativo.",
    "Какой? Похож на + acus.",
    "Я буду + N. Мне + imperativo. Пожалуйста.",
    "Этот/эта/это/эти. Такой/такая/такое/такие.",
    "Весь/вся/всё/все. Весь день, всю неделю.",
    "У меня болит + N. Vocabulario médico.",
    "Должен/должна/должны. Надо/нужно + inf.",
    "Нет + gen. Много/мало + gen. Сколько + gen.",
    "У + gen. Genitivo singular.",
    "Posesivos -ин/-ов. Чей?",
    "Acusativo animado masc. Verbos de percepción.",
    "Adjetivos en prepositivo sing.",
    "Следующий/прошлый. На + prepos + tiempo.",
    "Из + gen. С + gen. Откуда?",
    "Genitivo con у/из/с en contextos reales.",
    "Один (conc.) + N. Два/три/четыре + gen sing.",
    "Много/мало + gen pl. Genitivo plural.",
    "Час/часа/часов. Минута/минуты/минут. Без + gen.",
    "Genitivo plural de tiempo.",
    "Нет + gen (presente). Не было + gen (pasado).",
    "Genitivo plural animado (-ов/-ей/-∅).",
    "Mapa del aspecto: imperfectivo vs perfectivo.",
    "Imperfectivo: proceso, hábito, hecho general.",
    "Prefijos perfectivizantes. Futuro perfectivo.",
    "Perfectivo de cierre: закончить, ответить, etc.",
    "Не + imperf vs не + perf.",
    "Когда/как только + perfectivo.",
    "Perfectivo + сколько/много/мало.",
    "Найти, сломать, починить, построить, потерять.",
    "За- incoativo. Начать(ся). Cambio de estado.",
    "Пообещать + inf. Perfectivo de cumplimiento.",
    "Contraste aspectual integrado.",
    "Futuro perfectivo para promesas.",
    "Собираться/решить/хотеть + perf.",
    "Наверное/может быть + aspecto. Смочь/успеть.",
    "Imperativo perfectivo (скажите, помогите).",
    "Пере-/по- para repetición. Снова/опять.",
    "Надо/нужно/можно + perf.",
    "Надо/нужно/можно + imperf.",
    "Хотеть + imperf vs хотеть + perf.",
    "Síntesis aspectual completa."]

active_vocab = [
    ["familia","animales","bebidas","objetos"],
    ["ciudad","edificios","casa","direcciones"],
    ["profesiones","cortesía","personas"],
    ["verbos acción","rutina","trabajo","hogar"],
    ["deportes","juegos","ocio","compras"],
    ["construcción","comunicación","percepción"],
    ["personas","percepción","comprensión"],
    ["comunicación","nombres","memoria"],
    ["personas","objetos","medios"],
    ["cualidad","clima","sensación","velocidad"],
    ["posesión","familia","trabajo","tiempo"],
    ["ausencia","necesidad","posesión"],
    ["cualidades","descripción","personalidad"],
    ["colores","ropa","objetos","apariencia"],
    ["ciudad","instituciones","lugares"],
    ["espacio","posiciones","descripción urbana"],
    ["pasado","narrativa","cambio de estado"],
    ["clima","calendario","días","meses"],
    ["deportes","juegos","objetos fem."],
    ["personas","nombres","relaciones"],
    ["gustos","aficiones","relaciones"],
    ["planes","semana","futuro"],
    ["clima futuro","planes","existencia"],
    ["hora","números","tiempo"],
    ["compras","precios","dinero","descuentos"],
    ["alimentos","bebidas","comidas","salud"],
    ["pertenencia","objetos personales"],
    ["comunicación","temas","lectura"],
    ["percepción auditiva","visual","apariencia"],
    ["vivienda","pagos","emociones"],
    ["juegos","música","instrumentos","teatro"],
    ["movimiento","dirección","deíxis"],
    ["movimiento a pie","clima","planes"],
    ["experiencia","movimiento","ubicación"],
    ["transporte","viajes","desplazamientos"],
    ["transporte público","coche","a pie"],
    ["capacidad","permiso","prohibición"],
    ["causa","consecuencia","explicación"],
    ["cualidades","descripción","situaciones"],
    ["comparación","superlativos","calidad"],
    ["apariencia física","edad","altura","pelos/ojos"],
    ["comida","restaurante","pedidos","sabores"],
    ["señalamiento","identificación","comparación"],
    ["totalidad","tiempo","duración"],
    ["salud","cuerpo","síntomas","medicina"],
    ["obligación","deberes","necesidad","trabajo"],
    ["cantidad","ausencia","genitivo"],
    ["pertenencia","posesión","relaciones"],
    ["familia","nombres","pertenencia personal"],
    ["personas","animales","búsqueda","percepción"],
    ["ciudad","instituciones","descripción urbana"],
    ["tiempo relativo","planes","calendario"],
    ["origen","procedencia","viaje","institución"],
    ["médico","trabajo","citas","origen social"],
    ["cantidades","bebidas","compras"],
    ["cantidad","genitivo plural","objetos"],
    ["hora precisa","duración","tiempo"],
    ["duración","calendario","tiempo transcurrido"],
    ["ausencia","existencia","clima"],
    ["personas","animales","grupos"],
    ["aspecto verbal","verbos","contraste"],
    ["rutina","procesos","hábitos","descripciones"],
    ["resultado","formación verbal","prefijos"],
    ["finalización","resultado","acciones completas"],
    ["negación","matiz aspectual"],
    ["secuencia temporal","planes"],
    ["compras","escritura","lectura","preparación"],
    ["objetos","estado","cambios visibles"],
    ["inicio","emociones","salud","cambio"],
    ["obligaciones","promesas","planes cumplidos"],
    ["repaso aspectual","integración"],
    ["promesas","respuestas","planes inmediatos"],
    ["planes","intenciones","decisiones"],
    ["probabilidad","posibilidad","éxito"],
    ["peticiones","cortesía","instrucciones"],
    ["repetición","recurrencia"],
    ["obligación","permiso","necesidad completiva"],
    ["actividades en curso","duración","proceso"],
    ["deseo","intención","proceso vs resultado"],
    ["síntesis","integración","transición B1"]]

cabeceras = [l["title"] for l in existing]  # 80 titles

structures_list = [
    ["это + N","кто это?","что это?","и/а/но"],
    ["он/она/оно","где?","здесь/там/дома","справа/слева"],
    ["pronombre + N (profesión)","не + N","вы cortesía"],
    ["1ª conj. (-ать/-ять) presente","alternancia ск→щ, с→ш"],
    ["acusativo fem. (-а→-у)","играть в + juego","что + V?"],
    ["2ª conj. presente","alternancias 2ª"],
    ["acusativo animado","pronombres objeto directo","кого?"],
    ["как тебя зовут?","звать","у + gen pronombre"],
    ["plural regular","plural irregular","pluralia tantum"],
    ["как + adverbio","очень/так + adv","predicativo impersonal"],
    ["у + gen + есть","нет + gen"],
    ["есть opcional","нет + gen"],
    ["concordancia adj.","terminaciones adj."],
    ["adjetivos de color","concordancia color"],
    ["в/на + prepositivo","prepositivo sing."],
    ["рядом с","напротив + gen","слева/справа от"],
    ["pasado -л","был/была/было/были"],
    ["días, meses","времена года","было impersonal"],
    ["acusativo fem. (-а→-у,-я→-ю)","играть в"],
    ["acusativo animado masc.","кого?","nombres acusativo"],
    ["любить + O","любить + inf","любить + когда"],
    ["буду/будешь/будет + inf","в + día"],
    ["будет/будут","у + gen + будет"],
    ["números 1-20","который час?","во сколько?"],
    ["сколько стоит/стоят","стоить pasado/futuro"],
    ["есть (ем,ешь)","пить (пью,пьёшь)","comidas"],
    ["мой/твой/наш/ваш","его/её/их","чей?"],
    ["о/об + prepositivo","о ком/о чём"],
    ["слушать/слышать","смотреть/видеть","выглядеть"],
    ["платить за + acus.","adverbios frecuencia"],
    ["играть в/на","играть роль"],
    ["где? / куда?","дома/домой","здесь/сюда","там/туда"],
    ["идти (conj)","ходить (conj)","идти vs ходить"],
    ["был где? / ходил куда?"],
    ["ехать (conj)","ездить (conj)","ехать vs ездить"],
    ["на + transporte","на чём?","пешком"],
    ["уметь + inf","мочь (могу)","можно + inf","нельзя + inf"],
    ["почему?","потому что","поэтому"],
    ["concordancia adj. reforzada"],
    ["самый + adj","чем + caso"],
    ["какой?","похож на + acus."],
    ["я буду + N","мне + imperativo"],
    ["этот/эта/это/эти","такой/такая/такое/такие"],
    ["весь/вся/всё/все + tiempo"],
    ["у меня болит + N","vocab médico básico"],
    ["должен (conc.)","надо/нужно + inf"],
    ["нет + gen","много/мало + gen","сколько + gen"],
    ["у + gen","genitivo singular"],
    ["-ин posesivo","-ов posesivo","чей?"],
    ["acusativo animado masc.","кого?"],
    ["adjetivo + prepositivo"],
    ["следующий/прошлый","на + prepos + tiempo"],
    ["из + gen","с + gen","откуда?"],
    ["из/с contextos específicos"],
    ["один (conc.)","два/три/четыре + gen sing"],
    ["много/мало + gen pl","genitivo plural"],
    ["час/часа/часов","минута/минуты/минут","без + gen"],
    ["genitivo plural de tiempo"],
    ["нет + gen","не было + gen"],
    ["genitivo plural animado"],
    ["aspecto imperfectivo","aspecto perfectivo","pares aspectuales"],
    ["imperfectivo presente/pasado/futuro compuesto"],
    ["prefijos perfectivizantes","futuro perfectivo"],
    ["perfectivo de cierre"],
    ["не + imperfectivo","не + perfectivo"],
    ["когда + aspecto","как только + perfectivo"],
    ["perfectivo + cantidad"],
    ["perfectivo de resultado visible"],
    ["за- incoativo","начать + inf"],
    ["perfectivo de obligación cumplida"],
    ["contraste aspectual completo"],
    ["futuro perfectivo promesa"],
    ["собираться + perf","решить + perf","хотеть + perf"],
    ["наверное + aspecto","смочь + perf","успеть + perf"],
    ["imperativo perfectivo","cortesía"],
    ["пере- + V","по- + V","снова/опять"],
    ["modal + infinitivo perfectivo"],
    ["modal + infinitivo imperfectivo"],
    ["хотеть + imperf","хотеть + perf"],
    ["síntesis aspectual completa"]]

skills_bands = [
    ["production","recognition"]]*20 + [
    ["production","recognition","comprehension"]]*20 + [
    ["production","recognition","comprehension","grammar_transfer"]]*20 + [
    ["production","recognition","comprehension","grammar_transfer","listening"]]*20

cases_bands = [[]]*5 + [["acusativo"]]*5 + [["acusativo","genitivo"]]*10 + [["acusativo","genitivo","prepositivo"]]*20 + [["acusativo","genitivo","prepositivo","dativo"]]*20 + [["acusativo","genitivo","prepositivo","dativo","instrumental"]]*20

errors_main = [
    "Confundir кто/что, añadir есть, usar иметь",
    "Preposición con adverbios, género incorrecto",
    "Añadir есть con profesiones, ты en formal",
    "Terminaciones de 1ª conj., alternancias",
    "Nominativo en objeto directo, omitir в en играть",
    "Terminaciones 2ª conj.",
    "Nominativo en objeto animado, его posesivo/objeto",
    "Calco de llamar como звонить",
    "Terminaciones de plural irregular",
    "Adverbio vs adjetivo",
    "Usar иметь en posesión",
    "Usar есть en negación, genitivo tras нет",
    "No concordar adjetivo",
    "Colores invariables (беж, хаки)",
    "Usar nominativo tras в/на",
    "Calco de preposiciones españolas",
    "Olvidar género en pasado",
    "Género de meses",
    "Olvidar cambio -а→-у en acusativo",
    "No animar acusativo masculino",
    "Alternancia б→бл en люблю",
    "Conjugar también el infinitivo en futuro",
    "Usar presente donde va futuro",
    "Declinación час tras números",
    "No conjugar стоить",
    "Conjug. irregular есть (comer)",
    "No concordar posesivo",
    "Usar acusativo tras о",
    "Confundir par acción/resultado",
    "Omitir за en платить за",
    "Usar на con juegos",
    "Usar дома para dirección",
    "Usar идти para hábitos",
    "Usar ходил como 'fui' vs 'estuve'",
    "Usar ехать para hábitos",
    "Usar в con transporte",
    "Confundir уметь y мочь",
    "Confundir потому что y поэтому",
    "Posición del adjetivo",
    "Usar más literal (более)",
    "Confundir какой con который",
    "Forma я буду para pedidos",
    "Confundir это con этот",
    "Usar всё para todo genérico",
    "Partes del cuerpo: género inesperado",
    "No concordar должен",
    "Usar nominativo tras нет",
    "Terminaciones de genitivo",
    "Formación posesivos con nombres extranjeros",
    "No animar acusativo masc.",
    "Terminaciones adj. prepositivo",
    "Preposición con tiempo relativo",
    "Confundir из y с",
    "Usar из/с incorrecto",
    "Usar nominativo tras dos/tres/cuatro",
    "Terminaciones genitivo plural",
    "Declinación час tras números",
    "Años: год vs лет",
    "Usar нет en pasado",
    "Terminaciones genitivo plural animado",
    "No entender concepto aspectual",
    "Usar perfectivo para hábitos",
    "Elegir prefijo correcto",
    "Usar imperfectivo para cierre",
    "Usar solo imperfectivo en negación",
    "Usar imperfectivo en subordinadas temporales",
    "Usar imperfectivo para resultados puntuales",
    "Usar imperfectivo para cambios de estado",
    "Usar imperfectivo para inicio",
    "Usar imperfectivo para obligaciones cumplidas",
    "Todas las confusiones aspectuales",
    "Usar futuro compuesto para promesas",
    "Usar imperfectivo con intención completiva",
    "Aspecto incorrecto con modales posibilidad",
    "Usar imperativo imperfectivo para peticiones",
    "Usar mismo aspecto toda repetición",
    "Usar imperfectivo tras modales de completitud",
    "Usar perfectivo para procesos abiertos",
    "Usar solo imperfectivo tras хотеть",
    "Todos los errores aspectuales previos"]

curriculum = []
for i in range(80):
    lid = i + 1
    level = levels[i]
    
    entry = {
        "id": f"lesson_{lid:03d}",
        "number": lid,
        "title": cabeceras[i],
        "approxLevel": level,
        "status": status(lid),
        "communicativeTheme": themes[i],
        "summary": summary_map.get(f"lesson_{lid:03d}", cabeceras[i]),
        "communicativeObjectives": [obj_comm[i]],
        "grammarObjectives": [obj_gram[i]],
        "activeVocabularyThemes": active_vocab[i],
        "passiveVocabularyThemes": [],
        "newStructures": structures_list[i],
        "recycledStructures": [f"contenido de lecciones {max(1,lid-3)}-{lid-1}"] if lid > 1 else [],
        "cases": cases_bands[i],
        "skills": skills_bands[i],
        "typicalErrorsForSpanishSpeakers": [errors_main[i]],
        "criticalTargets": [{"id": s.replace(" ","_")[:30], "description": s} for s in structures_list[i][:3]],
        "expectedProduction": [obj_comm[i]],
        "expectedComprehension": [obj_gram[i]],
        "closingExam": exam_ok(lid),
        "unlockCriteria": f"Dominar targets críticos de la lección {lid} y pasar los exámenes" if lid <= 5 else "Pendiente de implementación",
        "previousLessonLinks": [f"Lecciones {max(1,lid-3)}-{max(1,lid-1)}"],
        "implementationNotes": f"{ex_by.get(lid,0)} ejercicios, {sum(exam_by.get(lid,{}).values())} exámenes implementados" if lid <= 5 else "Contenido planificado. Ningún ejercicio implementado todavía."
    }
    curriculum.append(entry)

with open(ROOT / "content/curriculum.json", "w") as f:
    json.dump(curriculum, f, ensure_ascii=False, indent=2)

print(f"CURRICULUM CREADO: {len(curriculum)} lecciones")
from collections import Counter
print(f"  Estados: {dict(Counter(l['status'] for l in curriculum))}")
for l in curriculum[:5]:
    print(f"  L{l['number']}: status={l['status']}, exam={l['closingExam']}")
print(f"  Última: L{curriculum[-1]['number']}: {curriculum[-1]['title']}")
print(f"  Campos por entry: {len(curriculum[0].keys())}")
